---
- name: Deploy Docker image
  hosts: localhost
  vars:
    image_name: devops-programme
    image_tag: v1
    listen_port: 3000
  tasks:
  - name: Pull Docker Image
    docker_image:
      name: "{{ image_name }}"
      source: pull
      tag: "{{ image_tag }}"
  - name: Start Docker container
    docker_container:
      name: "{{ image_name }}"
      image: "{{ image_name }}"
      ports:
      - "{{ listen_port | int }}:{{ listen_port | int }}"
      state: started